### ISSUE TITLE
Make sure we correctly infer primitive type

### ISSUE THREAD

**Issue by kanitw** [uwdata/compassql#116]
Forking from #103

- [ ] deal with an issue where the first item is null (I believe somehow it infers number | date as string if the first is null -- at least back then)

**Comment by kanitw** [comment]
I suspect if this is an issue since we're already using `inferAll`.  You can investigate this and close this if it's not really a problem.

**Comment by RileyChang** [comment]
Wrote a test with the following data:
[{a: null, b: 'June 21, 2000', c: 3, d: '3/3/333', e: "hi", f: 3.4, g: true}]
All primitive types were inferred correctly. `a` was inferred to be a `boolean`, but I don't think that's a problem. Closing this issue, we can reopen if we find an example that shows it's still a problem.
