### ISSUE TITLE
Rename `requireAllPropertiesSpecific` to `allowEnumSpecForProperties`

### ISSUE THREAD

**Issue by kanitw** [uwdata/compassql#130]
`requireAllPropertiesSpecific` still sound vague? 

I propose that we replace

`requireAllPropertiesSpecific:  true` with `allowEnumSpecForProperties: false` + vice versa
and  replace `if (requireAllPropertiesSpecific)`  with `if (!allowEnumSpecForProperties)` ... something like this? 

What do you think?

**Comment by felixcodes** [comment]
Will probably do that after all of the scale stuff is finished. 

reminder for future sleepy-felix: this means flipping the logic in some expressions as well...
