### ISSUE TITLE
Domain always return string

### ISSUE THREAD

**Issue by kanitw** [uwdata/compassql#132]
## For O, N  that are `number`

`keys()` method always return string, even for `number` fields.    We have to coerce those objects into appropriate types 

- [x] `number` --> do  `.map(x => +x)` to coerce to number
- [x] `date` --> need to coerce somehow 

## For Q

- [x] We should instead return `[min, max]`

**Comment by kanitw** [comment]
FYI, Just updated the description a bit more.

**Comment by kanitw** [comment]
FYI, I make [this hacky function in VLUI](https://github.com/vega/vega-lite-ui/blob/kw/q-filter/src/dataset/dataset.service.js#L108) for now.

**Comment by kanitw** [comment]
Is this fixed in #136?

**Comment by RileyChang** [comment]
@kanitw yes #136 fixes this issue, forgot to include that in the PR
