### ISSUE TITLE
Make cardinality correct for non-periodic timeUnits

### ISSUE THREAD

**Issue by RileyChang** [uwdata/compassql#166]
For time units such as `yearmonthdate`, the Schema class is determining incorrect cardinality. Datalib does not have built-in support for these kinds of time units, so it is currently inferring a time unit based off of the data itself.

**Comment by kanitw** [comment]
To clarify,

>  so it is currently inferring a time unit based off of the data itself.

And datalib would infer `year` for `yearmonthdate` time unit and thus produce incorrect result.

**Comment by RileyChang** [comment]
@kanitw I think we can close this issue? We are not using datalib at all for timeunit cardinality.
