### ISSUE TITLE
Relax constraint when having a field twice

### ISSUE THREAD

**Issue by kanitw** [uwdata/compassql#236]
Relax constraint when intentionally having a field twice.   

For example, the following input returns nothing:
![voyager_2](https://cloud.githubusercontent.com/assets/111269/16601875/9be7f948-42c4-11e6-97b6-296a7c4380d2.png)

{
"spec": {
   "data": {"url": "data/cars.json"},
   "mark": "point" or ?
   "encodings": [
      {"channel":"x", "field":"Cylinders", "type":"ordinal" }, 
      {"channel":"?","field":"Cylinders", "type":"ordinal"}
   ]}
}

**Comment by felixcodes** [comment]
We don't seem to have this issue anymore. Checked in editor and voyager.
