### ISSUE TITLE
Correctly infer date 

### ISSUE THREAD

**Issue by kanitw** [uwdata/compassql#91]
- [ ] Somehow in Voyager we infer date field in `cars.json` as `date` field but not in CompassQL. 
However, using datalib we only get it as integer/number.  We need to investigate why such difference happens.   (See "Univariate Summary" example in the editor.)

**Comment by kanitw** [comment]
- [ ] Release Date is just a year.

**Comment by RileyChang** [comment]
From discussion:
- no good way to infer date, must provide a way for user to provide that through a new API
- can pass the date format to vega-lite (once it is supported)  e.g. `parse: "data:%y"` for dates that are just a year

**Comment by kanitw** [comment]
Correction:

From discussion:
- no good way to infer *year*, must provide a way for user to provide that through a new API
- can pass the date format to vega-lite (once it is supported)  e.g. `parse: "data:%y"` for dates that are just a year

**Comment by kanitw** [comment]
Bumping this up.  

From "Univariate Summary" Demo:  year is inferred as string -- I'm not sure how should we address this, but definitely should address it ASAP. 

![vega_editor](https://cloud.githubusercontent.com/assets/111269/17252340/367233da-5561-11e6-9a04-9a007d446d69.png)

**Comment by kanitw** [comment]
It seems like the year field in vega-datasets's cars.json is different from the one in polestar/voyager.
